package org.gigahub.radio.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.gigahub.radio.dao.Station;
import org.gigahub.radio.dao.Stream;

import org.gigahub.radio.dao.StationDao;
import org.gigahub.radio.dao.StreamDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stationDaoConfig;
    private final DaoConfig streamDaoConfig;

    private final StationDao stationDao;
    private final StreamDao streamDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stationDaoConfig = daoConfigMap.get(StationDao.class).clone();
        stationDaoConfig.initIdentityScope(type);

        streamDaoConfig = daoConfigMap.get(StreamDao.class).clone();
        streamDaoConfig.initIdentityScope(type);

        stationDao = new StationDao(stationDaoConfig, this);
        streamDao = new StreamDao(streamDaoConfig, this);

        registerDao(Station.class, stationDao);
        registerDao(Stream.class, streamDao);
    }
    
    public void clear() {
        stationDaoConfig.getIdentityScope().clear();
        streamDaoConfig.getIdentityScope().clear();
    }

    public StationDao getStationDao() {
        return stationDao;
    }

    public StreamDao getStreamDao() {
        return streamDao;
    }

}
