package org.gigahub.radio.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STREAM.
 */
public class Stream {

    private Long id;
    private String url;
    private long stationId;

    public Stream() {
    }

    public Stream(Long id) {
        this.id = id;
    }

    public Stream(Long id, String url, long stationId) {
        this.id = id;
        this.url = url;
        this.stationId = stationId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public long getStationId() {
        return stationId;
    }

    public void setStationId(long stationId) {
        this.stationId = stationId;
    }

}
